{{- if .Values.daemonset.enabled }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "linx.name" . }}
    chart: {{ template "linx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "linx.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.rbac.enabled }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if .Values.env }}
        env:
{{ toYaml .Values.env | indent 12 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.daemonset.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.daemonset.volumeMounts | indent 12 }}
        {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.daemonset.volumes }}
      volumes:
{{ toYaml .Values.daemonset.volumes | indent 12 }}
      {{- end }}
{{ end }}