apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "linx.name" . }}
    chart: {{ template "linx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.deployment.service.type }}
  ports:
    - port: {{ .Values.deployment.service.port }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
  selector:
    app: {{ template "linx.name" . }}
    release: {{ .Release.Name }}